nodeLinker: node-modules

npmScopes:
  gamma-app:
    npmAlwaysAuth: true
    npmAuthToken: "${REPO_ACCESS_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com/"

yarnPath: .yarn/releases/yarn-1.22.17.cjs
