name: Example Request
description: Submit a request for an example
title: '[Example Request]: '
labels: ['Example Request']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Need an example of how to do something with tldraw?
  - type: textarea
    id: description
    attributes:
      label: What's example?
      description: Describe the example.
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/tldraw/tldraw/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
