name: Deploy bemo

# TODO: add some sort of production trigger
on:
  pull_request:
  push:
    branches:
      - main

env:
  CI: 1
  PRINT_GITHUB_ANNOTATIONS: 1
  TLDRAW_ENV: ${{ (github.ref == 'refs/heads/production' && 'production') || (github.ref == 'refs/heads/main' && 'staging') || 'preview'  }}
defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy bemo to ${{ (github.ref == 'refs/heads/production' && 'production') || (github.ref == 'refs/heads/main' && 'staging') || 'preview'  }}
    timeout-minutes: 15
    runs-on: ubuntu-latest-16-cores-open
    # TODO: dedicated separate environment for bemo
    environment: ${{ github.ref == 'refs/heads/production' && 'deploy-production' || 'deploy-staging' }}
    concurrency: ${{ github.ref == 'refs/heads/production' && 'bemo-production' || github.ref }}

    steps:
      - name: Notify initial start
        uses: MineBartekSA/discord-webhook@v2
        if: github.ref == 'refs/heads/production'
        with:
          webhook: ${{ secrets.DISCORD_DEPLOY_WEBHOOK_URL }}
          content: 'Preparing ${{ env.TLDRAW_ENV }} bemo deploy: ${{ github.event.head_commit.message }} by ${{ github.event.head_commit.author.name }}'

      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/actions/setup

      - name: Build types
        run: yarn build-types

      - name: Deploy
        run: yarn tsx scripts/deploy-bemo.ts
        env:
          RELEASE_COMMIT_HASH: ${{ github.sha }}
          GH_TOKEN: ${{ github.token }}

          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          DISCORD_DEPLOY_WEBHOOK_URL: ${{ secrets.DISCORD_DEPLOY_WEBHOOK_URL }}
          DISCORD_HEALTH_WEBHOOK_URL: ${{ secrets.DISCORD_HEALTH_WEBHOOK_URL }}
          WORKER_SENTRY_DSN: ${{ secrets.WORKER_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
